---
- name: "update apt packages"
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: create backend directory
  become: yes
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: copy backend files
  become: yes
  copy:
    src: artifact.tar.gz
    dest: ~/backend/artifact.tar.gz

- name: "Unarchive the copied tar file"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: starting the app
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start


