---
- name: "updadte apt packages"
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes" 
    
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: unarchive from the local into the remote server
  unarchive:
    src: "~/project/backend/artifact.tar.gz"
    dest: "~/web"
    remote_src: no

- name: Executing node
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start

# pm2 start ~/web/index.js -f    